### ISSUE TITLE
libcamera-dev not available on jetson

### ISSUE THREAD

**Issue by pgaskell** [MBot-Project-Development/mbot_sys_utils#4]
We need to make the install script check if it is a jetson and skip libcamera-dev

**Comment by sxy-sun** [comment]
This issue seems resolved by [this commit](https://github.com/MBot-Project-Development/mbot_sys_utils/commit/4b95c74ef28c2eac864be072713de32482345607) I'm going to close this issue for now to clean up outdated issues and PRs.
